version: '3.5'

services:
  2-3-frontend:
    image: 1.14-frontend
    ports:
      - 5000:5000
  2-3-backend:
    image: 1.14-backend
    ports:
      - 8080:8080
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment: 
      POSTGRES_PASSWORD: example
    container_name: db_backend

  redis:
    image: redis:6.2.4
