version: '3.5'

services:
  kurkkumopo-backend-docker:
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - ./model:/src/model
    depends_on:
      - kurkkumopo-training-docker

      kurkkumopo-frontend-docker:
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    depends_on:
      - kurkkumopo-backend-docker
    
  kurkkumopo-training-docker:
    build: ./ml-kurkkumopo-training
    volumes:
      - ./ml-kurkkumopo-training/imgs:/src/imgs
      - ./model:/src/model

volumes:
  model:

